version: "2"

services:
  guildbit:
    build: .
    links:
      - redis
      - murmur-rest
      - db
    environment:
      - FLASK_ENV=development
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8081
      - REDIS_HOST=redis:6379
      - DOCKER_TEST=1
      - C_FORCE_ROOT=true
    ports:
      - "8081:8081"
    volumes:
      - ".:/opt/guildbit"
      # - "./settings.py:/opt/guildbit/settings.py"
    command: /opt/guildbit/venv/bin/gunicorn -n guildbit -w 1 -b 0.0.0.0:8081 wsgi:app

  guildbit-tasks:
    build: .
    links:
      - redis
      - murmur-rest
      - db
    environment:
      - REDIS_HOST=redis:6379
      - C_FORCE_ROOT=true
    volumes:
      - ".:/opt/guildbit"
    command: /opt/guildbit/venv/bin/celery -A app.tasks worker --concurrency=2 -n guildbit-tasks -l info

  flower:
    image: mher/flower:0.9.7
    links:
      - redis
    environment:
      - REDIS_HOST=redis:6379
    ports:
      - "5555:5555"
    command: ["--app guildbit-tasks", "--broker=redis://redis:6379/0"]

  nginx:
    image: nginx
    volumes:
      - ./etc/nginx/conf.d/guildbit.com:/etc/nginx/conf.d/default.conf
      - ./etc/static:/opt/static
    ports:
      - "8082:80"
    links:
      - guildbit
    environment:
      - NGINX_HOST=guildbit.com
      - NGINX_PORT=80
    command: /bin/bash -c "exec nginx -g 'daemon off;'"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'guildbit'
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  murmur-rest:
    image: alfg/murmur-rest:latest
    environment:
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - APP_DEBUG=True
      - MURMUR_ICE_HOST=murmurd
      - MURMUR_ICE_PORT=6502
      - ENABLE_AUTH=True
      - USERS=admin:password,admin2:password2
    ports:
      - "8080:8080"
    links:
      - murmurd

  murmurd:
    image: alfg/murmur
    ports:
      - "127.0.0.1:6502:6502"
      - "50000-50050:50000-50050"
    volumes:
      - ./etc/murmur.ini:/etc/murmur/murmur.ini
      - murmurdb:/var/lib/murmur/

volumes:
  pgdata:
  redisdata:
  murmurdb: